[CmdletBinding()]
param([string]$DxcPath = $env:CHEEKY_DXC)
$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $PSScriptRoot
if (-not $DxcPath) { $DxcPath = Join-Path $root '.reference\OptiScaler-DLSSNR-PreSR-Multipass\OptiScaler\shaders\shader_tools\dxc.exe' }
if (-not (Test-Path -LiteralPath $DxcPath)) { throw 'Set CHEEKY_DXC or pass -DxcPath with a SPIR-V-capable DirectX Shader Compiler.' }
$out = Join-Path $root 'build\vulkan-shaders'
New-Item -ItemType Directory -Force -Path $out | Out-Null
$jobs = @(
    @{Name='overlay0'; Header='standalone\vulkan_overlay_shader.hpp'; Prefix='third_party\reshade\deps\imgui\backends\cheeky_overlay_color.h'; Entry='main'; Stage='ps_6_0'; Mode=0; U=0; B=0},
    @{Name='overlay1'; Header='standalone\vulkan_overlay_shader.hpp'; Prefix='third_party\reshade\deps\imgui\backends\cheeky_overlay_color.h'; Entry='main'; Stage='ps_6_0'; Mode=1; U=0; B=0},
    @{Name='overlay2'; Header='standalone\vulkan_overlay_shader.hpp'; Prefix='third_party\reshade\deps\imgui\backends\cheeky_overlay_color.h'; Entry='main'; Stage='ps_6_0'; Mode=2; U=0; B=0},
    @{Name='overlay3'; Header='standalone\vulkan_overlay_shader.hpp'; Prefix='third_party\reshade\deps\imgui\backends\cheeky_overlay_color.h'; Entry='main'; Stage='ps_6_0'; Mode=3; U=0; B=0},
    @{Name='composite16'; Header='src\d3d12_composite_shader.hpp'; Entry='CompositeMain'; U=2; B=3; Format='rgba16f'},
    @{Name='composite32'; Header='src\d3d12_composite_shader.hpp'; Entry='CompositeMain'; U=2; B=3; Format='rgba32f'},
    @{Name='composite8'; Header='src\d3d12_composite_shader.hpp'; Entry='CompositeMain'; U=2; B=3; Format='rgba8'},
    @{Name='motion'; Header='src\crop_motion_shader.hpp'; Entry='main'; U=1; B=2; Format='rg32f'},
    @{Name='peripheral_motion'; Header='src\peripheral_shaders.hpp'; Symbol='motion_convert_shader_source'; Entry='Main'; U=1; B=2; Format='rg32f'},
    @{Name='peripheral_color'; Header='src\peripheral_shaders.hpp'; Symbol='color_downsample_shader_source'; Entry='Main'; U=1; B=2; Format='rgba16f'},
    @{Name='peripheral_depth'; Header='src\peripheral_shaders.hpp'; Symbol='depth_downsample_shader_source'; Entry='Main'; U=1; B=2; Format='r32f'},
    @{Name='nr_guides'; Header='src\nr_guide_shader.hpp'; Entry='main'; U=2; B=4; Formats=@('rg32f','r32f')},
    @{Name='nr_copy16'; Header='src\peripheral_shaders.hpp'; Symbol='color_downsample_shader_source'; Entry='Main'; U=1; B=2; Format='rgba16f'},
    @{Name='nr_copy32'; Header='src\peripheral_shaders.hpp'; Symbol='color_downsample_shader_source'; Entry='Main'; U=1; B=2; Format='rgba32f'},
    @{Name='nr_copy8'; Header='src\peripheral_shaders.hpp'; Symbol='color_downsample_shader_source'; Entry='Main'; U=1; B=2; Format='rgba8'},
    @{Name='nr_encode16'; Header='src\nr_codec_shader.hpp'; Entry='EncodeMain'; U=3; B=5; Format='rgba16f'},
    @{Name='nr_encode32'; Header='src\nr_codec_shader.hpp'; Entry='EncodeMain'; U=3; B=5; Formats=@('rgba32f','rgba16f')},
    @{Name='nr_encode8'; Header='src\nr_codec_shader.hpp'; Entry='EncodeMain'; U=3; B=5; Formats=@('rgba8','rgba16f')},
    @{Name='nr_decode16'; Header='src\nr_codec_shader.hpp'; Entry='DecodeMain'; U=3; B=5; Formats=@('rgba16f','rgba16f')},
    @{Name='nr_decode32'; Header='src\nr_codec_shader.hpp'; Entry='DecodeMain'; U=3; B=5; Formats=@('rgba32f','rgba16f')},
    @{Name='nr_decode8'; Header='src\nr_codec_shader.hpp'; Entry='DecodeMain'; U=3; B=5; Formats=@('rgba8','rgba16f')},
    @{Name='nr_border16'; Header='src\nr_codec_shader.hpp'; Entry='BorderMain'; U=3; B=5; Formats=@('rgba16f','rgba16f')},
    @{Name='nr_border32'; Header='src\nr_codec_shader.hpp'; Entry='BorderMain'; U=3; B=5; Formats=@('rgba32f','rgba16f')},
    @{Name='nr_border8'; Header='src\nr_codec_shader.hpp'; Entry='BorderMain'; U=3; B=5; Formats=@('rgba8','rgba16f')}
)
$text = "// Generated by scripts/build-vulkan-shaders.ps1 from shared shader sources.`n#pragma once`n#include <cstdint>`nnamespace cheeky::foveated_dlss::vulkan_shaders {`n"
foreach ($job in $jobs) {
    $header = Get-Content -LiteralPath (Join-Path $root $job.Header) -Raw
    $pattern = if ($job.Symbol) { '(?s)' + $job.Symbol + '\[\] = R"\((.*?)\)";' } else { '(?s)R"\((.*?)\)";' }
    $match = [regex]::Match($header, $pattern)
    if (-not $match.Success) { throw "Cannot extract $($job.Header)" }
    $source = Join-Path $out "$($job.Name).hlsl"
    $shader = $match.Groups[1].Value
    if($job.Prefix) {
        $prefix=Get-Content -LiteralPath (Join-Path $root $job.Prefix) -Raw
        $shader="#define CHEEKY_COLOR_MODE $($job.Mode)`n"+[regex]::Match($prefix,'(?s)R"\((.*?)\)";').Groups[1].Value+$shader
    }
    if ($job.Formats) {
        $script:formatIndex = 0
        $shader = [regex]::Replace($shader, 'RWTexture', { param($m)
            $format = $job.Formats[$script:formatIndex++]
            '[[vk::image_format("' + $format + '")]] RWTexture'
        })
    } else { $shader = $shader.Replace('RWTexture', ('[[vk::image_format("' + $job.Format + '")]] RWTexture')) }
    [IO.File]::WriteAllText($source, $shader)
    $binary = Join-Path $out "$($job.Name).spv"
    $stage=if($job.Stage){$job.Stage}else{'cs_6_0'}
    & $DxcPath -spirv -T $stage -E $job.Entry -O3 '-fspv-target-env=vulkan1.1' -fvk-use-dx-layout -fvk-u-shift $job.U 0 -fvk-b-shift $job.B 0 -Fo $binary $source
    if ($LASTEXITCODE -ne 0) { throw "Shader compilation failed: $($job.Name)" }
    $bytes = [IO.File]::ReadAllBytes($binary)
    $words = for ($i=0; $i -lt $bytes.Length; $i+=4) { '0x{0:X8}U' -f [BitConverter]::ToUInt32($bytes,$i) }
    $text += "inline constexpr std::uint32_t $($job.Name)[] = {`n"
    for ($i=0; $i -lt $words.Count; $i+=8) { $text += ($words[$i..([Math]::Min($i+7,$words.Count-1))] -join ',') + ",`n" }
    $text += "};`n"
}
$text += "}`n"
[IO.File]::WriteAllText((Join-Path $root 'src\vulkan_shaders.hpp'),$text)
