"""Compile the Direct3D shaders embedded in CheekyFoveatedDLSS.

Run with Python and the Windows SDK fxc.exe, for example:
    python scripts/build-d3d-shaders.py --fxc "C:\\Program Files (x86)\\Windows Kits\\10\\bin\\10.0.26100.0\\x64\\fxc.exe"
"""

import argparse
from pathlib import Path
import re
import subprocess
import tempfile


ROOT = Path(__file__).resolve().parent.parent
# name, source file, C++ raw-string symbol, HLSL entry, profile, optimization
SHADERS = [
    ("composite11", "src/d3d11_composite_shader.hpp", "d3d11_composite_shader_source", "CompositeMain", "cs_5_0", 3),
    ("composite12", "src/d3d12_composite_shader.hpp", "composite_shader_source", "CompositeMain", "cs_5_1", 3),
    ("crop_motion", "src/crop_motion_shader.hpp", "crop_motion_shader_source", "main", "cs_5_0", 3),
    ("crop_depth", "src/crop_motion_shader.hpp", "crop_depth_shader_source", "main", "cs_5_0", 3),
    ("peripheral11_color", "src/d3d11_peripheral_dlaa.cpp", "color_downsample_shader_source", "Main", "cs_5_0", 3),
    ("peripheral11_depth", "src/d3d11_peripheral_dlaa.cpp", "depth_downsample_shader_source", "Main", "cs_5_0", 3),
    ("peripheral11_motion", "src/d3d11_peripheral_dlaa.cpp", "motion_downsample_shader_source", "Main", "cs_5_0", 3),
    ("transport_depth11", "src/d3d11_d3d12_transport.cpp", "depth_shader_source", "Main", "cs_5_0", 3),
    ("peripheral12_motion", "src/peripheral_shaders.hpp", "motion_convert_shader_source", "Main", "cs_5_1", 3),
    ("peripheral12_color", "src/peripheral_shaders.hpp", "color_downsample_shader_source", "Main", "cs_5_1", 3),
    ("peripheral12_depth", "src/peripheral_shaders.hpp", "depth_downsample_shader_source", "Main", "cs_5_1", 3),
    ("peripheral12_rr", "src/peripheral_shaders.hpp", "rr_guide_downsample_shader_source", "Main", "cs_5_1", 3),
    ("nr_guides", "src/nr_guide_shader.hpp", "nr_guide_shader", "main", "cs_5_0", 1),
    ("nr_encode", "src/nr_codec_shader.hpp", "nr_codec_shader", "EncodeMain", "cs_5_1", 3),
    ("nr_decode", "src/nr_codec_shader.hpp", "nr_codec_shader", "DecodeMain", "cs_5_1", 3),
    ("nr_border", "src/nr_codec_shader.hpp", "nr_codec_shader", "BorderMain", "cs_5_0", 1),
    ("debug_marker12", "src/debug_marker12.hpp", "source", "main", "cs_5_0", 3),
]


def source_for(path: Path, symbol: str) -> str:
    text = path.read_text(encoding="utf-8")
    match = re.search(r"\b" + re.escape(symbol) + r'\[\]\s*=\s*R"\((.*?)\)";', text, re.S)
    if not match:
        raise ValueError(f"Missing shader source {symbol} in {path}")
    return match.group(1)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--fxc", type=Path, required=True, help="Path to Windows SDK fxc.exe")
    parser.add_argument("--check", action="store_true", help="Fail if the checked-in shader bytecode is stale")
    args = parser.parse_args()
    output = [
        "// Generated by scripts/build-d3d-shaders.py. Do not edit by hand.",
        "#pragma once",
        "#include <cstddef>",
        "#include <cstdint>",
        "namespace cheeky::foveated_dlss::d3d_shaders {",
        "struct ShaderBytecode { const void* data; std::size_t size; };",
    ]
    total = 0
    with tempfile.TemporaryDirectory() as directory:
        temp = Path(directory)
        for name, file, symbol, entry, profile, optimization in SHADERS:
            hlsl = temp / f"{name}.hlsl"
            compiled = temp / f"{name}.cso"
            hlsl.write_text(source_for(ROOT / file, symbol), encoding="utf-8")
            subprocess.run(
                [str(args.fxc), "/nologo", f"/O{optimization}", "/T", profile,
                 "/E", entry, "/Fo", str(compiled), str(hlsl)],
                check=True,
            )
            data = compiled.read_bytes()
            total += len(data)
            output.append(f"// {file}: {symbol}, {entry}, {profile}, O{optimization}")
            output.append(f"inline constexpr std::uint8_t {name}_data[] = {{")
            for offset in range(0, len(data), 16):
                output.append("    " + ", ".join(f"0x{b:02x}" for b in data[offset:offset + 16]) + ",")
            output.append("};")
            output.append(f"inline constexpr ShaderBytecode {name}{{{name}_data, sizeof({name}_data)}};")
    output.append("}")
    destination = ROOT / "src/d3d_shaders.hpp"
    generated = "\n".join(output) + "\n"
    if args.check:
        if not destination.exists() or destination.read_text(encoding="utf-8") != generated:
            raise SystemExit(f"Stale shader bytecode: rerun {Path(__file__).name} without --check")
        print(f"Verified {len(SHADERS)} shaders, {total} bytecode bytes")
    else:
        destination.write_text(generated, encoding="utf-8", newline="\n")
        print(f"Generated {destination}: {len(SHADERS)} shaders, {total} bytecode bytes")


if __name__ == "__main__":
    main()
